### ISSUE TITLE
More pt language

### ISSUE THREAD

**Issue by EWE07** [Caslus/wukong#3]
https://github.com/Caslus/wukong/blob/8e5ea599c1ab8b3acd66d83275a52769adfed270/src/locale.json#L111

"Rodar Javascript é muito perigoso!"

:0

**Comment by Caslus** [comment]
aqui está desse jeito de propósito mesmo kkkkkk

**Comment by EWE07** [comment]
pera tu e fala português ou tu é inglês? kk

**Comment by Caslus** [comment]
> pera tu e fala português ou tu é inglês? kk

sou brasileiro 😂😂

**Comment by EWE07** [comment]
ata
