### ISSUE TITLE
[bug] JSON error

### ISSUE THREAD

**Issue by MigPlayer6032** [Caslus/wukong#5]
The locale.json file has a JSON formatting error, @Caslus!

[This line](https://github.com/Caslus/wukong/blob/e9380a628cccd0a620b53372be3d636e5d0561a4/src/locale.json#L148) has an error: a comma ( , ) is missing at the end.

**Comment by MigPlayer6032** [comment]
Bom, agora você me deixou confuso: eu não sei se você fala inglês ou português, mas na dúvida vou colocar o issue em português também :D

**Comment by MigPlayer6032** [comment]
O arquivo `locale.json` tem um erro de formatação JSON!
[Essa linha](https://github.com/Caslus/wukong/blob/e9380a628cccd0a620b53372be3d636e5d0561a4/src/locale.json#L148) tem um erro: falta uma vírgula ( , ) no final.

**Comment by Caslus** [comment]
opa amigo, muito obrigado por avisar, já estarei editando aqui 💖
